/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.demoneach.dbgenerator;


import static org.slf4j.Logger.ROOT_LOGGER_NAME;

import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import lombok.extern.slf4j.Slf4j;
import ru.demoneach.dbgenerator.entity.Parameters;
import ru.demoneach.dbgenerator.helper.ConfigParser;
import ru.demoneach.dbgenerator.helper.PgSQLDataGenerator;

@Slf4j
public class App {
    
    public static void main(String[] args) throws Exception {
        Logger rootLogger = (Logger) LoggerFactory.getLogger(ROOT_LOGGER_NAME);
        rootLogger.setLevel(Level.INFO);
        Parameters parameters = new ConfigParser().parseConfig();

        log.info("Parameters: {}", parameters);
        PgSQLDataGenerator pgSQLDataGenerator = new PgSQLDataGenerator(parameters);
        pgSQLDataGenerator.generateDataForTables(parameters);
    }
}
