package ru.demoneach.dbgenerator.helper;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import ru.demoneach.dbgenerator.entity.*;
import java.sql.DriverManager;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

@EnabledIfEnvironmentVariable(named = "DBGEN_TEST_DATABASE", matches = ".+")
class GeneratedColumnsPostgresTest {
    @Test
    void allStrategiesUseServerDefaultsAcrossRepeatedRuns() throws Exception {
        ConnectionParameters connection = new ConnectionParameters();
        connection.setHost(System.getenv().getOrDefault("DBGEN_TEST_HOST", "localhost"));
        connection.setPort(System.getenv().getOrDefault("DBGEN_TEST_PORT", "5432"));
        connection.setDbName(System.getenv("DBGEN_TEST_DATABASE"));
        connection.setUsername(System.getenv().getOrDefault("DBGEN_TEST_USER", "postgres"));
        connection.setPassword(System.getenv().getOrDefault("DBGEN_TEST_PASSWORD", ""));
        String url = "jdbc:postgresql://%s:%s/%s".formatted(connection.getHost(), connection.getPort(), connection.getDbName());
        String schema = "dbgen_test_" + UUID.randomUUID().toString().replace("-", "");
        try (var conn = DriverManager.getConnection(url, connection.getUsername(), connection.getPassword());
             var sql = conn.createStatement()) {
            sql.execute("CREATE SCHEMA " + schema);
            try {
                sql.execute("CREATE TABLE " + schema + ".mixed (id serial PRIMARY KEY, "
                        + "always_id int GENERATED ALWAYS AS IDENTITY UNIQUE, "
                        + "default_id int GENERATED BY DEFAULT AS IDENTITY UNIQUE, value int, "
                        + "twice bigint GENERATED ALWAYS AS (value::bigint * 2) STORED)");
                sql.execute("CREATE TABLE " + schema + ".defaults (id serial PRIMARY KEY, value int DEFAULT 7)");
                int total = 0;
                for (Strategy strategy : Strategy.values()) {
                    Parameters parameters = new Parameters();
                    parameters.setConnectionParameters(connection);
                    parameters.setStrategy(strategy);
                    parameters.setAmountOfEntries(3);
                    parameters.setBatch(2);
                    parameters.setBatchSave(2);
                    parameters.setTablesToGenerate(List.of(schema + ".mixed", schema + ".defaults"));
                    parameters.setFieldGenerationRules(Map.of(schema + ".mixed.value", new Rule(RuleType.CONST, List.of("11"))));
                    for (int repeat = 0; repeat < 2; repeat++) {
                        new PgSQLDataGenerator(parameters).generateDataForTables(parameters);
                        total += 3;
                        try (var rows = sql.executeQuery("SELECT count(*) FROM " + schema + ".mixed WHERE value=11 AND twice=22")) {
                            assertTrue(rows.next());
                            assertEquals(total, rows.getInt(1));
                        }
                        try (var rows = sql.executeQuery("SELECT count(*) FROM " + schema + ".defaults WHERE value=7")) {
                            assertTrue(rows.next());
                            assertEquals(total, rows.getInt(1));
                        }
                    }
                }
                // A regular insert after all generators must still obtain fresh sequence values.
                sql.execute("INSERT INTO " + schema + ".mixed (value) VALUES (12)");
                sql.execute("INSERT INTO " + schema + ".defaults DEFAULT VALUES");
            } finally {
                sql.execute("DROP SCHEMA " + schema + " CASCADE");
            }
        }
    }
}
